services:
  wg-easy:
    image: weejewel/wg-easy:7
    container_name: wg-easy

    # Host network – moves wg0 into the host namespace
    network_mode: "host"
    
    # Gives full privileges so WireGuard can
    # load kernel modules even after a host reboot without errors.
    privileged: true

    environment:
      - WG_HOST=${VPN_SERVER_URL}          # e.g., your IP or domain
      - PASSWORD=${VPN_ADMIN_PASSWORD}
      - WG_PORT=51820
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_DEFAULT_ADDRESS=10.13.13.x
    volumes:
      - ./wg-easy-config:/etc/wireguard
    #ports:
    #  - "51820:51820/udp"
    #  - "51821:51821/tcp"
    #cap_add:
    #  - NET_ADMIN
    #  - SYS_MODULE
    #sysctls:
    #  - net.ipv4.ip_forward=1
    restart: unless-stopped



    #networks:
    #  - proxy-network

networks:
  proxy-network:
    external: true